module.exports = {
  'axle': 'As in the generic definition, a rod that serves to attach a wheel to a bicycle and provides support for bearings on which the wheel rotates. Also sometimes used to describe suspension components, for example a swing arm pivot axle',
  'bar ends': 'Extensions at the end of straight handlebars to allow for multiple hand positions',
  'bar plugs': 'plugs for the ends of handlebars',
  'basket': 'cargo carrier',
  'bearing': 'a device that facilitates rotation by reducing friction',
  'bell': 'an audible device for warning pedestrians and other cyclists',
  'belt-drive': 'Alternative to chain-drive',
  'brake cable': 'See Cable',
  'bottle cage': 'A holder for a water bottle',
  'bottom bracket': 'The bearing system that the pedals (and cranks) rotate around. Contains a spindle to which the crankset is attached and the bearings themselves. There is a bearing surface on the spindle, and on each of the cups that thread into the frame. The bottom bracket may be overhaulable (an adjustable bottom bracket) or not overhaulable (a cartridge bottom bracket). The bottom bracket fits inside the bottom bracket shell, which is part of the bicycle frame',
  'brake': 'Devices used to stop or slow down a bicycle. Rim brakes and disc brakes are operated by brake levers, which are mounted on the handlebars. Band brake is an alternative to rim brakes but can only be installed at the rear wheel. Coaster brakes are operated by pedaling backward',
  'Brake lever': 'A lever for actuating a bicycle brake',
  'brifter': 'combined shifter and brake lever control',
  'braze-on': 'A fitting protruding from a frame to provide attachment, typically for cable housings or tire pumps and similar accessories',
  'cable guide': 'A fitting below the bottom bracket which guides a piece of bare inner bowden cable around a corner',
  'cable': 'A metal cable enclosed in part by a metal and plastic housing that is used to connect a control, such as a brake or shifting lever, to the device it activates',
  'cartridge bearing': 'A type of bearing that is not user-serviceable, but must be replaced as a unit',
  'cassette': 'A group of stacked sprockets on the rear wheel of a bicycle with a rear derailleur',
  'chain': 'A system of interlinking pins, plates and rollers that transmits power from the front sprocket(s) to the rear sprocket(s)',
  'chainguard': 'Cover for the entire chain either totally encasing (sometimes containing oil) or \'incomplete\'. Either way, designed to keep clothing from fouling the chain. See also Skirtguard',
  'chainring': 'one of the front gears, attached to a crank',
  'chainstay': 'a pair of tubes on a bicycle frame that runs from the bottom bracket to the rear fork ends',
  'chain tensioner': 'a device to maintain proper chain tension',
  'chaintug': 'a device to aid in setting the proper chain tension',
  'cluster': 'a bicycle cogset, either a freewheel, or cassette',
  'cogset': 'the set of rear sprockets that attaches to the hub on the rear wheel',
  'cone': 'holds bearings in place, pressed against the cup',
  'cotter': 'pin for attaching cottered cranks',
  'coupler': 'to connect tubing together',
  'crankset or chainset': 'composed of cranks and at least one chainring',
  'cup': 'receives ball bearings which roll along its inner surface; integrated on most conventional hubs or can be pressed into older bottom bracket shells. See also Cone',
  'cyclocomputer': 'an electronic accessory that measures and displays instantaneous and cumulative speed and distance. Often provides other measurements such as heart rate',
  'derailleur hanger': 'a piece on the rear dropout that the derailleur attaches to.',
  'derailleur': 'an assembly of levers, usually cable actuated, that moves the chain between sprockets on a cassette or chainring assembly',
  'down tube': 'tube on the bicycle frame that runs from the head tube to the bottom bracket',
  'dropout': 'a bicycle rear fork end that allows the rear wheel to be removed without first derailing the chain. The term dropout is often incorrectly used to refer to any fork end, but not all fork ends are dropouts',
  'dustcap': 'any cap serving to keep dirt and contamination out of an assembly. Common over crank bolts, often plastic',
  'dynamo': 'bicycle lighting component, also known as generator',
  'eyelet': 'attachment point on frame, fork, or dropout for fenders, racks, etcetera, or a hole through which a spoke nipple passes through the rim so it may attach to a spoke',
  'electronic Gear-Shifting System': 'not simply a type of shifter or a type of derailleur, a complete system with switches instead of levers, wires instead of Bowden cables, and motor-driven derailleurs that must all work together',
  'fairing': 'a full or partial covering for a bicycle to reduce aerodynamic drag or to protect the rider from the elements',
  'fender or mudguard': 'curved pieces of metal or plastic above the tires which catch and redirect road spray thrown up by the tires, allowing the rider to remain relatively clean. May come in pairs',
  'ferrule': 'a metal or plastic sleeve used to terminate the end of a cable housing',
  'fork': 'a mechanical assembly that integrates a bicycle\'s frame to its front wheel and handlebars, allowing steering by virtue of its steerer tube',
  'fork end': 'paired slots on a fork or frame at which the axle of the wheel is attached. See also Dropout',
  'frame': 'the mechanical core of a bicycle, the frame provides points of attachment for the various components that make up the machine. The term is variously construed, and can refer to the base section, always including the bottom bracket, or to base frame, fork, and suspension components such as a shock absorber',
  'freehub': 'a ratcheting assembly onto which a cog or cassette is mounted that allows the bicycle to coast without the pedals turning',
  'freewheel': 'a ratcheting assembly that incorporates one or more cogs and allows the bicycle to coast without the pedals turning',
  'gusset': 'plates added to the outsides of frame tubes to strengthen joints. These are more commonly seen on BMX and mountain bikes',
  'hanger': 'part of frame or an attachment to the frame to which the derailleur is attached (see Derailleur hanger)',
  'handlebar': 'a lever attached, usually using an intermediary stem, to the steerer tube of the fork. Allows steering and provides a point of attachment for controls and accessories',
  'handlebar plug': 'see Bar plugs',
  'handlebar tape': 'a tape wound around dropped handlebars so as to provide padding and grip, usually cork or cloth, sometimes foam rubber',
  'head badge': 'manufacturer\'s or brand logo affixed to the head tube',
  'head tube': 'the tube of a bicycle frame that contains the headset',
  'headset': 'the bearings that form the interface between the frame and fork steerer tube',
  'hood': 'the rubber brake lever covering on bikes with drop style handle bars',
  'hub': 'the core of a wheel; contains bearings and, in a traditional wheel, has drilled flanges for attachment of spokes',
  'hub dynamo': 'a generator inside one of the hubs for powering lights or other accessories',
  'hub gear': 'a gearbox mounted inside the hub, 3-speed is common, 5, 7 are available ("Sturmey-Archer") and Rohloff make a 14-speed hub. Cable operated by one or two cables',
  'indicator': 'a turn signal',
  'inner tube': 'a bladder that contains air to inflate a tire. Has a Schrader, "Woods"/"Dunlop" or Presta valve for inflation and deflation',
  'jockey wheel': 'one of two small sprockets of the rear derailleur that guide the chain',
  'kickstand': 'a folding attachment used for assisting a bicycle to stand up on its own. Usually mounts to frame near bottom bracket, sometimes near rear dropouts',
  'lawyer lips': 'also called a "lawyer tab", a retention device on the dropouts of the front fork to prevent inadvertent loss of the front wheel in the case it is not properly secured',
  'locknut': 'a nut designed not to loosen due to vibration',
  'lockring': 'a ring, usually metal, of varying design, that serves to retain a component in place',
  'lug': 'a metal connector used to align frame components where they join each other',
  'luggage carrier': 'any accessory equipment designed to carry tools, gear or cargo',
  'master link': 'a bicycle chain accessory that allows convenient removal and reconnection of an installed bicycle chain without the need for a chain tool',
  'nipple': 'a specialized nut that most commonly attaches a spoke to a wheel rim. In some systems, it provides attachment to the hub',
  'pannier': 'cloth zippered storage bags that mount to sides of luggage racks. Pronounced pan-ear, or pan-yer (an old English word, not French)',
  'pedal': 'mechanical interface between foot and crank arm. There are two general types; one secures the foot with a mechanical clamp or cage and the other has no connection to lock the foot to the pedal',
  'peg': 'short metal tube, about 6 inches (15 cm) long and 2 inches (5.1 cm) fastened to one or both ends of the wheel axles to either enable the rider perform certain tricks or provide a place for extra riders to stand or rest',
  'portage strap': 'a strap (usually made of leather) attached to the inside of the bike frame, designed to make carrying the bike over one\'s shoulder easier',
  'quick release': 'a skewer with a lever on one end that loosens when the lever is flipped. Used for releasing wheels and seat posts',
  'rack': 'a rack that attaches behind the seat, usually with stays to the rear dropouts, that serves as a general carrier',
  'reflector': 'reflects light to make bicycle evident when the illuminated by headlights of other vehicles. Usually required by law but held in disdain by many cyclists',
  'training wheels': 'used for assisting balance. Comes in pair. Useful for first time bicyclists',
  'rim': 'that part of a wheel to which the tire is attached and often forms part of the braking mechanism',
  'rotor': 'a device that allows the handlebars and fork to revolve indefinitely without tangling the rear brake cable',
  'safety levers': 'extension levers, and interrupt brake levers. Used to apply brakes in order for the bicycle to slow down or suddenly stop',
  'saddle': 'what a bicyclist sits on',
  'seat rails': 'a metal framework over which saddle covering is stretched. The seat post attaches to the seat rails by means of a clamp',
  'seat lug': 'a frame lug on the top of the seat tube serving as a point of attachment for a clamp to secure the seat post',
  'seat tube': 'the roughly vertical tube in a bicycle frame running from the seat to the bottom bracket',
  'seat bag': 'a small storage accessory hung from the back of a seat',
  'seatpost': 'a post that the seat is mounted to. It slides into the frame\'s seat tube and is used to adjust ride height depending how far into the seat tube it is inserted',
  'seatstay': 'frame components, small diameter tubes running from top of seat tube to rear dropouts',
  'shaft-drive': 'alternate to chain-drive',
  'shifter': 'gear shifting control',
  'shock absorber': 'for bicycles with suspensions, a device that limits the rate at which suspension rebounds after absorbing an impact',
  'side view mirror': 'aids in looking at the sides prior to moving slowly or turning to the left or to the right',
  'skirt guard': 'a device fitted over the rear wheel of a bicycle to prevent a long skirt, coat or other trailing clothes or luggage from catching in the wheel, or in the gap between the rim and the brakes',
  'spindle': 'an axle around which a pedal rotates; threaded at one end to screw into crank arms',
  'spoke': 'connects wheel rim to hub. Usually wire with one end swaged to form a head and one threaded end. A typical wheel has 36 spokes',
  'steering tube': 'a tube on top of a fork that is inserted through frame and serves as an axle by means of which bicycle can be steered',
  'stem': 'a bracket used to attach handlebars to steerer tube of fork. Usually secured by pinch bolts',
  'tire': 'as in common usage. Usually pneumatic. A tubular tire is glued to the wheel rim; most tires use tubes, but tubeless tires and rims are increasingly common',
  'toe clips': 'a metal or plastic cage attached to a pedal. Usually has an adjustment strap. Secures foot to pedal for increased control and more effective transfer of power from foot to drive chain',
  'top tube': 'frame member leading from steerer tube to seat tube',
  'valve': 'port for adding or releasing air from the inner tube. Two types are commonly used: Presta and Schrader. A third type, the Woods/Dunlop valve, can still be found in Europe and Asia.',
  'wheel': 'as in common usage. Traditionally and most commonly spoked',
  'wingnut': 'for attaching wheels before the development of the quick release skewer'
}
